/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: /mnt/e/everest/fstar-master/kremlin/krml -fc89 -fc89 -I /mnt/e/everest/fstar-master/hacl-star/code/lib/kremlin -I /mnt/e/everest/fstar-master/kremlin/kremlib/compat -I /mnt/e/everest/fstar-master/hacl-star/specs -I /mnt/e/everest/fstar-master/hacl-star/specs/old -I . -ccopt -march=native -verbose -ldopt -flto -I ../bignum -tmpdir x25519-c -I ../bignum -tmpdir x25519-c -bundle Hacl.Curve25519=* -minimal -add-include "kremlib.h" -skip-compilation x25519-c/out.krml -o x25519-c/Hacl_Curve25519.c
 * F* version: a4bbc2d1
 * KreMLin version: 920d217c
 */


#ifndef __Hacl_Curve25519_H
#define __Hacl_Curve25519_H


#include "kremlib.h"

extern FStar_UInt128_uint128 FStar_Int_Cast_Full_uint64_to_uint128(uint64_t x0);

void Hacl_Curve25519_crypto_scalarmult(uint8_t *mypublic, uint8_t *secret, uint8_t *basepoint);

#define __Hacl_Curve25519_H_DEFINED
#endif
