/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: /mnt/e/everest/fstar-master/kremlin/krml -fc89 -fc89 -I /mnt/e/everest/fstar-master/hacl-star/code/lib/kremlin -I /mnt/e/everest/fstar-master/kremlin/kremlib/compat -I /mnt/e/everest/fstar-master/hacl-star/specs -I /mnt/e/everest/fstar-master/hacl-star/specs/old -I . -ccopt -march=native -verbose -ldopt -flto -tmpdir ed25519-c -I ../bignum -I ../curve25519 -I ../hash ed25519-c/out.krml -skip-compilation -minimal -add-include "kremlib.h" -bundle Hacl.Ed25519=*
 * F* version: a4bbc2d1
 * KreMLin version: 47733122
 */


#ifndef __Hacl_Ed25519_H
#define __Hacl_Ed25519_H


#include "kremlib.h"

extern FStar_UInt128_uint128 FStar_Int_Cast_Full_uint64_to_uint128(uint64_t x0);

typedef uint8_t *Hacl_Ed25519_uint8_p;

typedef uint8_t *Hacl_Ed25519_hint8_p;

void Hacl_Ed25519_sign(uint8_t *signature, uint8_t *secret, uint8_t *msg, uint32_t len1);

bool Hacl_Ed25519_verify(uint8_t *output, uint8_t *msg, uint32_t len1, uint8_t *signature);

void Hacl_Ed25519_secret_to_public(uint8_t *output, uint8_t *secret);

#define __Hacl_Ed25519_H_DEFINED
#endif
