
/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: /mnt/f/dev/sec/everest/fstar-master/kremlin/krml -fc89-scope -fc89 -fnocompound-literals -fc89-scope -fnocompound-literals -fc89-scope -I /mnt/f/dev/sec/everest/fstar-master/hacl-star/code/lib/kremlin -I /mnt/f/dev/sec/everest/fstar-master/kremlin/kremlib -I /mnt/f/dev/sec/everest/fstar-master/hacl-star/specs -I . -ccopt -march=native -verbose -ldopt -flto -I ../bignum -tmpdir x25519-c -drop FStar,Prims,C.Loops.Spec.Loops,Spec.*,Hacl.Spec.*,Hacl.Cast,Hacl.UInt.*,Hacl.Endianness,Hacl.UInt8,Hacl.UInt16,Hacl.UInt32,Hacl.UInt64,Hacl.UInt128 -add-include "kremlin/testlib.h" /mnt/f/dev/sec/everest/fstar-master/kremlin/kremlib/testlib.c -no-prefix Hacl.Test.X25519 -bundle Hacl.Curve25519=Hacl.Bignum,Hacl.Bignum.*,Hacl.EC,Hacl.EC.*,LowStar.* -skip-compilation x25519-c/out.krml -o x25519-c/Hacl_Curve25519.c
 * F* version: f464bd99
 * KreMLin version: d5538f7d
 */

#include "kremlib.h"
#ifndef __Hacl_Curve25519_H
#define __Hacl_Curve25519_H


#include "kremlin/testlib.h"

void Hacl_EC_crypto_scalarmult(uint8_t *mypublic, uint8_t *secret, uint8_t *basepoint);

void Hacl_Curve25519_crypto_scalarmult(uint8_t *mypublic, uint8_t *secret, uint8_t *basepoint);

#define __Hacl_Curve25519_H_DEFINED
#endif
